export const DATA_TASK_ADD = 'DATA_TASK_ADD';
export const DATA_TASK_EDIT = 'DATA_TASK_EDIT';
export const DATA_TASK_DELETE = 'DATA_TASK_DELETE';
export const DATA_TASK_UPDATE = 'DATA_TASK_UPDATE';
export const DATA_DELETE_ALL = 'DATA_DELETE_ALL';
export const DATA_CREATE_FAKE_TASKS = 'DATA_CREATE_FAKE_TASKS';
export const FORM_CHANGE_STATUS = 'FORM_CHANGE_STATUS';
export const DATA_TASK_CHANGE_STATUS = 'DATA_TASK_CHANGE_STATUS';